version: 2

project_name: kc

release:
  github:
    owner: kypello-io
    name: kc
  name_template: "v{{.Version}}"
  mode: append

env:
  - CGO_ENABLED=0

builds:
  - goos:
      - linux
      - darwin
      - windows
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm
      - ppc64le
      - s390x

    goarm:
      - "7"

    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: s390x

    flags:
      - -tags=kqueue
      - -trimpath

    ldflags:
      - -s -w
      - -X github.com/kypello-io/kc/cmd.Version={{.Version}}
      - -X github.com/kypello-io/kc/cmd.ReleaseTag={{.Tag}}
      - -X github.com/kypello-io/kc/cmd.CommitID={{.FullCommit}}
      - -X github.com/kypello-io/kc/cmd.ShortCommitID={{.ShortCommit}}
      - -X github.com/kypello-io/kc/cmd.CopyrightYear={{time "2006"}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: kc
    package_name: kc
    vendor: Kypello
    homepage: https://github.com/kypello-io/kc
    maintainer: Kypello <dev@kypello.io>
    description: Kypello Client (kc) provides a modern alternative to UNIX commands like ls, cat, cp, mirror, diff, find etc. It supports filesystems and Amazon S3 compatible cloud storage service (AWS Signature v2 and v4).
    license: AGPL-3.0
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk
    contents:
      - src: LICENSE
        dst: /usr/share/kc/LICENSE
      - src: README.md
        dst: /usr/share/kc/README.md

checksum:
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    signature: ${artifact}.sigstore.json

docker_signs:
  - cmd: cosign
    args:
      - sign
      - --yes
      - ${artifact}
    artifacts: manifests

kos:
  - repository: ghcr.io/kypello-io/kc
    tags:
      - "{{.Version}}"
      - "{{.Tag}}"
      - latest
    bare: true
    base_image: cgr.dev/chainguard/static
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v7
      - linux/ppc64le
      - linux/s390x
    sbom: none

sboms:
  - artifacts: archive

changelog:
  disable: true
