FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

LABEL maintainer="Kypello <dev@kypello.io>"

COPY kc /usr/bin/
COPY CREDITS /licenses/CREDITS
COPY LICENSE /licenses/LICENSE
COPY NOTICE  /licenses/NOTICE

RUN  \
     microdnf update --nodocs --assumeyes && \
     microdnf install ca-certificates --nodocs --assumeyes && \
     microdnf clean all

ENTRYPOINT ["kc"]
